services:
  # db:
  #   container_name: db
  #   image: mariadb
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
  #     - MARIADB_DATABASE=${MARIADB_DATABASE}
  #     - MARIADB_USER=${MARIADB_USER}
  #     - MARIADB_PASSWORD=${MARIADB_PASSWORD}
  #   volumes:
  #     - ./db/init:/docker-entrypoint-initdb.d
  #     - ./db/data:/var/lib/mysql
  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin
  #   restart: unless-stopped
  #   env_file: .env
  #   ports:
  #     - 81:80
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=db
  #     - PMA_USER=${MARIADB_USER}
  #     - PMA_PASSWORD=${MARIADB_PASSWORD}
  #   depends_on:
  #     - db
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    # restart: unless-stopped
    # env_file: .env
    ports:
      - 3001:3000
    # environment:
    #   - DB_HOST=db
    #   - DB_USER=${MARIADB_USER}
    #   - DB_PASS=${MARIADB_PASSWORD}
    #   - DB_NAME=${MARIADB_DATABASE}
    #   - DB_PORT=3306
    #   - VUE_HOST=${VUE_HOST}:5000
    # volumes:
    #   - ./api:/app
    # depends_on:
    #   - db
  # vue:
  #   container_name: vue
  #   build:
  #     context: ./vue
  #     dockerfile: Dockerfile
  #     args:
  #       VUE_APP_API_HOST: ${API_HOST}:3001
  #   restart: unless-stopped
  #   working_dir: /app
  #   env_file: .env
  #   ports:
  #     - 5000:80
  #   depends_on: 
  #     - api