services:
  db:
    container_name: db
    image: mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - ./db/custom-config.cnf:/etc/mysql/conf.d/custom-config.cnf
      - ./db/add-on:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=3306
      - VUE_HOST=${VUE_HOST}
    depends_on:
      - db
  
  vue:
    container_name: vue
    build:
      context: ./vue
      dockerfile: Dockerfile
      args:
        VUE_APP_API_HOST: ${API_HOST}
    restart: unless-stopped
    working_dir: /app
    env_file: .env
    ports:
      - 5000:80
    depends_on: 
      - api