# Use Ubuntu as the base image
FROM ubuntu:24.04

# Set environment variables
ENV NODE_VERSION=18
ENV NPM_VERSION=9
ENV REPO_URL="https://github.com/vives-project-xp/PX3-Campus-Games.git"
ENV BRANCH="main"
ENV PORT 3000
ENV PORT_FRONT 5000

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install Node.js and npm
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm@$NPM_VERSION

# Set working directory
WORKDIR /app

# Clone the repo
RUN git clone --branch $BRANCH $REPO_URL /app

# Set working directory for frontend
WORKDIR /app/docker/vue

# Install frontend dependencies
RUN npm install --legacy-peer-deps

# Install vue-cli-service globally
RUN npm install -g @vue/cli-service

# Set working directory for backend
WORKDIR /app/docker/api

# Install backend dependencies
RUN npm install

# Expose necessary ports
EXPOSE 5000 3000

# Pull latest changes and start both frontend and backend
CMD ["sh", "-c", "cd /app && git pull origin $BRANCH && cd Backend && npm run dev & cd ../Frontend/vives-card-game && npm run serve"]